### ISSUE TITLE
Cloudflare instructions and screenshots out of date

### ISSUE THREAD

**Issue by bdon** [protomaps/docs#3]
Name is now `worker.js`

* unminify code

**Comment by Lewiscowles1986** [comment]
> **Note:** cloudflare docs. Is it https://github.com/protomaps/docs/blob/255c5c9/deploy/cloudflare.md?
  
> **Note:** Minified code seems to be output from build process to `https://protomaps.github.io/PMTiles/index.js`

**Comment by bdon** [comment]
I had a todo to disable that minification: https://github.com/protomaps/PMTiles/pull/290 that's done now.

**Comment by Lewiscowles1986** [comment]
Well done you, 50% complete

https://developers.cloudflare.com/pages/platform/functions/bindings/ doesn't say anything about worker.js; but now the source is minified, I do see it's default export is some form of url handler. Thing is that it looks different to those examples, so I can't help but wonder if I'm looking in the wrong place.

**Comment by bdon** [comment]
Resolved by #58
