### ISSUE TITLE
Maplibre instructions out of date

### ISSUE THREAD

**Issue by lenalebt** [protomaps/docs#39]
Hey,

just a short heads-up: https://github.com/protomaps/docs/blob/main/pmtiles/maplibre.md contains outdated instructions for maplibre-gl. https://maplibre.org/maplibre-gl-js/docs/examples/pmtiles/ says how it should be done with newer maplibre-gl versions.

It's also mentioned on the frontpage of https://protomaps.com/ in the outdated way.

This is about `maplibregl.addProtocol("pmtiles",protocol.tile)` which should read like this:

```
maplibregl.addProtocol('pmtiles', (request) => {
        return new Promise((resolve, reject) => {
            const callback = (err, data) => {
                if (err) {
                    reject(err);
                } else {
                    resolve({data});
                }
            };
            protocol.tile(request, callback);
        });
    });
```

**Comment by bdon** [comment]
PR is open on MapLibre docs: https://github.com/maplibre/maplibre-gl-js/pull/4248

The newest major `pmtiles` version (v3) supports the new `addProtocol` in maplibre v4 and is also backwards compatible with maplibre <v4, so the code in the docs should still work.

**Comment by bdon** [comment]
https://github.com/maplibre/maplibre-gl-js/pull/4248 was merged.
