### ISSUE TITLE
Dead link for `addProtocol` in Maplibre Docs

### ISSUE THREAD

**Issue by mizmay** [protomaps/docs#75]
https://github.com/protomaps/docs/blob/9206bd29636f4c25b54ebee791877bda2f9a58a9/pmtiles/maplibre.md?plain=1#L12

Should be https://maplibre.org/maplibre-gl-js/docs/API/functions/addProtocol/

**Comment by bdon** [comment]
Thanks, can you open a PR?

**Comment by mizmay** [comment]
#79
